### ISSUE TITLE
在最新版本中，发现的需要前端帮忙解决的问题

### ISSUE THREAD

**Issue by Leungx** [ustc17-program-educated-online-game/TheGame#2]
- 测试并修复成功：

1. 登录注册信息逻辑正确
2. 前后端codelist数据格式一致
3. 主页已完成部分路由正确

- 需要前端帮忙解决的问题：（或者是我理解错误请指出orz）

1. 地图编辑器部分，发现逻辑问题：编辑好地图之后点击保存或者测试后似乎未将编辑的地图保存，而是直接加载与开始游戏部分同样的模块，以至于无法测试自己编辑的地图。（即发现test和edit部分貌似没有共享自己编辑的地图数据）
2. 游戏界面部分，修复后端传送数据bug后，发现前端对于得到的后端数据处理时出现了小bug，而导致小人无法改变状态。

**Comment by ShadowTinker** [comment]
“修复后端传送数据bug”是我在第一个issue中提到的吗？如果是的话小人可以进行移动吗？因为小人的方向状态还没有实现，因此不知道是整体出了问题还是因为暂时没实现

**Comment by Leungx** [comment]
> “修复后端传送数据bug”是我在第一个issue中提到的吗？如果是的话小人可以进行移动吗？因为小人的方向状态还没有实现，因此不知道是整体出了问题还是因为暂时没实现

是的。但是小人还是无法移动，我跟踪bug发现貌似是GameInterface.vue的64行赋值失败

**Comment by ShadowTinker** [comment]
OK，我根据控制台信息改下试试

**Comment by ShadowTinker** [comment]
最新的commit中已修复游戏界面的代码处理问题，需要更复杂的地图进行进一步调试

**Comment by Ta1ly** [comment]
> * 测试并修复成功：
> 
> 1. 登录注册信息逻辑正确
> 2. 前后端codelist数据格式一致
> 3. 主页已完成部分路由正确
> 
> * 需要前端帮忙解决的问题：（或者是我理解错误请指出orz）
> 
> 1. 地图编辑器部分，发现逻辑问题：编辑好地图之后点击保存或者测试后似乎未将编辑的地图保存，而是直接加载与开始游戏部分同样的模块，以至于无法测试自己编辑的地图。（即发现test和edit部分貌似没有共享自己编辑的地图数据）
> 2. 游戏界面部分，修复后端传送数据bug后，发现前端对于得到的后端数据处理时出现了小bug，而导致小人无法改变状态。

**Comment by Ta1ly** [comment]
地图编辑器逻辑部分现在已经补充完成。之前由于在后端的Game 的view中地图保存存在一个数据类型的小bug，导致无法保存上传的地图，现在已经修复，地图可以正常保存和测试。但是不知道现在是否已经完成了地图共享的后端数据库支持（可能需要等待社区功能建设完善），因此共享功能暂时没有开放。
