### ISSUE TITLE
关于游戏主界面的测试

### ISSUE THREAD

**Issue by Zhaoxingbo** [ustc17-program-educated-online-game/TheGame#3]
- 在数据库中添加了关卡1-5的地图，对应的地图编号为10001-10005，提供了编号为1000的测试地图。如果需要更改地图或者添加其他地图，可以修改django_sys/game/initial_database.py文件。initial_database.py文件需要在python manage.py shell中运行。

- 暂时注释掉了后端代码解析中条件判断的else部分

- 在游戏主界面测试中遇到的一些问题：

1. 在右侧代码执行完毕后没有弹出相应的提示信息（成功或者失败）。（成功后的提示信息最好可以包含前往下一关的按钮）
2. 每次执行完右侧代码后，在下次执行前应该将小人复位，而不是从上一次结束的位置继续。（或者添加一个只复位小人，不清除代码的按钮）
3. 若代码中操作数过多，在小人没有执行完所有操作前点击清空按钮，小人复位后会继续未完成的操作。

- 关卡选择界面中每个关卡对应的开始游戏按钮尚未实现

**Comment by wuchao-li** [comment]
- 第一个问题已经解决，添加了成功和失败的信息卡，会在右侧代码执行完毕后弹出。

- 另外，补充一下第二个问题，如果不按清空，小人不复位，代码会出现转向后行走方向不对的bug。我建议将代码清空和复位小人功能分开，所以我添加了一个复位的按钮，不过需要有人补充逻辑。

**Comment by ShadowTinker** [comment]
主界面中第二第三的逻辑已补全

**Comment by Zhaoxingbo** [comment]
最新版本中，连续运行的问题已经修复，目前尚未发现其他问题。
单步运行仍有较多问题：代码运行完无提示信息；代码运行完点击复位小人后，再运行小人不动；代码运行中途点击复位小人，再运行会继续未完成的代码。（基本与连续运行一开始的问题相同）

**Comment by ShadowTinker** [comment]
已同步单步调试逻辑
